# Generated by Django 2.1.7 on 2019-02-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slist', '0002_auto_20190212_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(),
        ),
    ]
